[project]
name = "bee-classifier"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "imageio>=2.37.0",
    "torch>=2.5.1",
    "torchvision>=0.20.1",
]
